name: "Checkmarx Test on ASoC"

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:

permissions:
  security-events: write
  contents: read

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run AppScan
        uses: ankurraina66/checkmarx_test@main
        env:
          GH_APP_ID: ${{ secrets.APPSCAN_GH_APP_ID }}
          GH_APP_INSTALLATION_ID: ${{ secrets.APPSCAN_GH_APP_INSTALLATION_ID }}
          GH_APP_PRIVATE_KEY: ${{ secrets.APPSCAN_GH_APP_PRIVATE_KEY }}
        with:
          baseurl: https://cloud.appscan.com
          asoc_key: ${{ secrets.ASOC_KEY }}
          asoc_secret: ${{ secrets.ASOC_SECRET }}
          application_id: e17e1275-c881-43f4-af46-4b4e5c57114f
          dynamic_scan_type: dast
          starting_URL: https://demo.testfire.net?mode=demo
          login_method: userpass
          login_user: jsmith
          login_password: demo1234
          network: public
          fail_for_noncompliance: false
          wait_for_analysis: true
