name: "Build Summary & PR Decoration for HCL AppScan SAST"

on:
  workflow_dispatch:

  push:
    branches:
      - main

  pull_request:


permissions:
  contents: read
  security-events: write
  pull-requests: write
  issues: write


jobs:

  scan:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4


      # SAST scan for BOTH push and PR
      - name: Run AppScan SAST scan

        uses: ankurraina66/test_sast_action_orca@main

        with:

          asoc_key: ${{ secrets.ASOC_KEY }}

          asoc_secret: ${{ secrets.ASOC_SECRET }}

          application_id: 16574fc8-59c8-4675-ade2-885877e0a392

          wait_for_analysis: true

          # NEW → identify PR scans
          is_pr_scan: ${{ github.event_name == 'pull_request' }}

          pr_number: ${{ github.event.pull_request.number }}

          repo_name: ${{ github.repository }}

          branch_name: ${{ github.head_ref || github.ref_name }}



      - name: Upload SARIF to GitHub Security tab

        if: always() && hashFiles('appscan-results.sarif') != ''

        uses: github/codeql-action/upload-sarif@v4

        with:

          sarif_file: appscan-results.sarif
