name: "Build Summary & PR Decoration for HCL AppScan SAST"

on:
  workflow_dispatch:

  push:
    branches:
      - main

  pull_request:


permissions:
  contents: read
  security-events: write
  pull-requests: write
  issues: write


jobs:

  scan:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4


      # Run AppScan SAST scan
      - name: Run AppScan SAST scan

        uses: ankurraina66/test_sast_action_orca@main

        with:

          asoc_key: ${{ secrets.ASOC_KEY }}
          asoc_secret: ${{ secrets.ASOC_SECRET }}
          application_id: 21b194f5-cea5-4ff6-a4d1-a03103a3e2fb

      # Upload PR HTML report
      - name: Upload PR report

        if: github.event_name == 'pull_request'

        uses: actions/upload-artifact@v4

        with:

          name: appscan-pr-report

          path: appscan-pr-report.html


      # Upload build summary HTML report
      - name: Upload Build report

        if: github.event_name != 'pull_request'

        uses: actions/upload-artifact@v4

        with:

          name: appscan-build-report

          path: appscan-build-summary-report.html
